name: awkward-main

on:
  push:
    branches: ['main']
    paths-ignore: ['**.md', 'docs/**']
  pull_request:
    paths-ignore: ['**.md', 'docs/**']
  workflow_dispatch:

concurrency:
  group: 'awkward-main-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install
      run: |
        python3 -m pip install pip wheel -U
        python3 -m pip install -q --no-cache-dir -e .[complete,test]
        python3 -m pip uninstall -y awkward && pip install git+https://github.com/scikit-hep/awkward.git@main --no-deps
    - name: Run tests
      run: |
        python3 -m pytest
