name: minimum-dependencies

on:
  push:
    branches: ['main']
    paths-ignore: ['**.md', 'docs/**']
  pull_request:
    paths-ignore: ['**.md', 'docs/**']
  workflow_dispatch:

concurrency:
  group: 'minimum-dependencies-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        lfs: true
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.9"
    - name: Install
      run: |
        python3 -m pip install pip build wheel pytest -U
        python3 -m pip install -e . -vv
    - name: Run tests
      run: |
        python3 -m pytest
