name: "PR title"

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
  workflow_dispatch:

permissions:
  pull-requests: read


concurrency:
  group: 'pr-title-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v6
      with:
        ignoreLabels: |
          pre-commit.ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
