name: Publish to PyPI

on:
  push:
  release:


jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        lfs: true

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"

    - name: Build
      run: |
        python3 -m pip install pip wheel build -U
        python3 -m build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags')
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
